---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: sample-producer-job
  name: sample-producer-job
spec:
  completions: 1
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: sample-producer-job
    spec:
      restartPolicy: OnFailure
      activeDeadlineSeconds: 300
      containers:
      - name: sample-producer
        image: strimzi/hello-world-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: demo-kafka-bootstrap:9093
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: demo-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef:
                name: user-demo
                key: user.crt
          - name: USER_KEY
            valueFrom:
              secretKeyRef:
                name: user-demo
                key: user.key
          - name: TOPIC
            value: greetings
          - name: DELAY_MS
            value: "100"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000"
